name: Release-Linux-x86_64

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

  pull_request:  # fires on every push to any open PR branch
    branches: [main_disable]
  
permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      TARGET: x86_64-unknown-linux-gnu
      BINARY_NAME: adqa-${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || 'v0.0.0' }}-linux-x86_64-unknown-linux-gnu
      PYTHON_URL: "https://github.com/astral-sh/python-build-standalone/releases/download/20260211/cpython-3.12.12+20260211-x86_64-unknown-linux-gnu-install_only_stripped.tar.gz"
      PYTHON_SHA256: "1dbaa624a09e15afe7efbdac08d42993135a68db8d34f986ef6977a6d77bdc3c"

    steps:
      - uses: actions/checkout@v6
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ env.TARGET }}

      # - name: Install Build Dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y libreadline-dev libedit-dev libncursesw5-dev libsqlite3-dev libssl-dev libffi-dev libexpat1-dev libbz2-dev liblzma-dev uuid-dev zlib1g-dev tcl-dev tk-dev libx11-dev libxcb1-dev libxau-dev

      - name: Setup Standalone Python
        shell: bash
        run: |
          mkdir -p standalone_python
          cd standalone_python
          curl -sfSL "${{ env.PYTHON_URL }}" -o python.tar.gz

          # checksum check
          echo "$PYTHON_SHA256  python.tar.gz" | sha256sum -c -

          tar -xf python.tar.gz
          mv python/ ../python_env
          cd ..
          chmod +x python_env/bin/python3

      - name: Install Backend Packages into Bundled Python
        run: ./python_env/bin/python3 -m pip install .

      - name: Build TUI
        working-directory: adqa-tui
        shell: bash
        run: |
          PYTHON_ROOT_DIR=$(realpath "../python_env")
          LIB_SO=$(find "$PYTHON_ROOT_DIR" -name "libpython3.12.so*" | head -n 1)
          if [ -z "$LIB_SO" ]; then
            echo "Error: libpython3.12.so not found"
            exit 1
          fi
          LIB_DIR=$(dirname "$LIB_SO")
          
          cat <<CONF | sed 's/^[[:space:]]*//' > ../pyo3-config.txt
          implementation=CPython
          version=3.12
          shared=true
          lib_name=python3.12
          lib_dir=$LIB_DIR
          pointer_width=64
          build_flags=
          CONF
          
          export PYO3_CONFIG_FILE="$(pwd)/../pyo3-config.txt"
          
          # Use shared linking and set RPATH so the binary finds libpython3.12.so in the bundle
          # $ORIGIN refers to the directory containing the executable
          export RUSTFLAGS="-L $LIB_DIR -Clink-arg=-Wl,-rpath,\$ORIGIN/python/lib"
                    
          cargo build --release --target ${{ env.TARGET }}

      - name: Prepare Standalone Package
        shell: bash
        run: |
          mkdir -p ${{ env.BINARY_NAME }}
          cp adqa-tui/target/${{ env.TARGET }}/release/adqa-tui ${{ env.BINARY_NAME }}/
          cp adqa-tui/target/${{ env.TARGET }}/release/adqa-cli ${{ env.BINARY_NAME }}/
          cp -r python_env ${{ env.BINARY_NAME }}/python

          rm -rf ${{ env.BINARY_NAME }}/python/share ${{ env.BINARY_NAME }}/python/include
          find ${{ env.BINARY_NAME }}/python -name "__pycache__" -type d -exec rm -rf {} + || true

          tar -I 'zstd -19' -cf "${{ env.BINARY_NAME }}.tar.zst" "${{ env.BINARY_NAME }}/"
      
      - name: Upload to Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: "v0.1.0-beta" # Disable later
          files: ${{ env.BINARY_NAME }}.tar.zst
          draft: true
          prerelease: true
