name: Release-apple-darwin-x86_64-aarch64-tar.zst-dmg

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

  pull_request:  # fires on every push to any open PR branch
    branches: [main_disable]

permissions:
  contents: write

jobs:
  build-macos:
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            python_url: "https://github.com/astral-sh/python-build-standalone/releases/download/20260211/cpython-3.12.12+20260211-x86_64-apple-darwin-install_only_stripped.tar.gz"
            PYTHON_SHA256: "a84ac7a36d465bc6eb68db84540fdb5da04333900e2c3cb34b5d454f2022048c"

          - target: aarch64-apple-darwin
            python_url: "https://github.com/astral-sh/python-build-standalone/releases/download/20260211/cpython-3.12.12+20260211-aarch64-apple-darwin-install_only_stripped.tar.gz"
            PYTHON_SHA256: "22625deaf5757e7c266cf1a096c9151a06b598b1e14632a2ec9993d58ec5fe84"
    
    runs-on: macos-latest
    env:
      BINARY_NAME: adqa-${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || 'v0.0.0' }}-${{ matrix.target }}
    steps:
      - uses: actions/checkout@v5
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Setup Standalone Python
        shell: bash
        run: |
          mkdir -p standalone_python
          cd standalone_python
          curl -sfSL "${{ matrix.python_url }}" -o python.tar.gz
          
          # checksum check
          echo "${{ matrix.PYTHON_SHA256 }}  python.tar.gz" | sha256sum -c -

          tar -xf python.tar.gz
          mv python/ ../python_env
          cd ..
          chmod +x python_env/bin/python3

      - name: Install Backend Packages into Bundled Python
        run: ./python_env/bin/python3 -m pip install .

      - name: Build TUI
        working-directory: adqa-tui
        shell: bash
        run: |
          PYTHON_ROOT_DIR=$(realpath "../python_env")
          LIB_FILE=$(find "$PYTHON_ROOT_DIR" -name "libpython3.12.dylib" | head -n 1)
          LIB_DIR=$(dirname "$LIB_FILE")
          
          cat <<CONF | sed 's/^[[:space:]]*//' > ../pyo3-config.txt
          implementation=CPython
          version=3.12
          shared=true
          lib_name=python3.12
          lib_dir=$LIB_DIR
          pointer_width=64
          build_flags=
          CONF
          
          export PYO3_CONFIG_FILE="$(pwd)/../pyo3-config.txt"
          export RUSTFLAGS="-L $LIB_DIR"
          
          cargo build --release --target ${{ matrix.target }}
      
      - name: Prepare Standalone Package
        shell: bash
        run: |
          mkdir -p ${{ env.BINARY_NAME }}
          cp adqa-tui/target/${{ matrix.target }}/release/adqa-tui ${{ env.BINARY_NAME }}/
          cp adqa-tui/target/${{ matrix.target }}/release/adqa-cli ${{ env.BINARY_NAME }}/
          cp -r python_env ${{ env.BINARY_NAME }}/python

          rm -rf ${{ env.BINARY_NAME }}/python/share ${{ env.BINARY_NAME }}/python/include
          find ${{ env.BINARY_NAME }}/python -name "__pycache__" -type d -exec rm -rf {} + || true
          
          # Fix rpath so the binary finds the bundled dylib
          install_name_tool -add_rpath "@executable_path/python/lib" ${{ env.BINARY_NAME }}/adqa-tui || true
          install_name_tool -add_rpath "@executable_path/python/lib" ${{ env.BINARY_NAME }}/adqa-cli || true

          tar --use-compress-program='zstd -19' -cf "${{ env.BINARY_NAME }}.tar.zst" "${{ env.BINARY_NAME }}/"
      
      - name: Upload to Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: "v0.1.0-beta" # Disable later
          files: ${{ env.BINARY_NAME }}.tar.zst
          draft: true
          prerelease: true
      
      # Create dmg
      # You have to sign your .dmg files by pay 99$/year to apple or will be blocked by gatekeeper.
      - name: Code sign
        shell: bash
        run: |
            # Ad-hoc sign the binaries (the '-' means no identity/self-signed)
            codesign --force --deep --sign - ${{ env.BINARY_NAME }}/adqa-tui
            codesign --force --deep --sign - ${{ env.BINARY_NAME }}/adqa-cli

      - name: hdiutil
        shell: bash
        run: |
          hdiutil create \
            -volname "${{ env.BINARY_NAME }}" \
            -srcfolder "${{ env.BINARY_NAME }}" \
            -ov -format UDBZ \
            -imagekey bzip2-level=9 \
            "${{ env.BINARY_NAME }}.dmg"

      - name: Upload to Release
        uses: softprops/action-gh-release@v3
        with:
          #tag_name: "v0.1.0-beta" # Disable later
          files: ${{ env.BINARY_NAME }}.dmg
          #draft: true
          prerelease: true

