name: Release-win-x86_64-aarch64-zip-msi

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  build-windows:
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            arch: x64
            runner: windows-latest
            python_url: "https://github.com/astral-sh/python-build-standalone/releases/download/20260211/cpython-3.12.12+20260211-x86_64-pc-windows-msvc-install_only_stripped.tar.gz"
            python_sha256: "93bf8e8c05ede0077b197a29c99ebdaf253497f27190097494265150b4e70ba8"
          
          - target: aarch64-pc-windows-msvc
            arch: arm64
            runner: windows-11-arm
            python_url: "https://github.com/astral-sh/python-build-standalone/releases/download/20260211/cpython-3.12.12+20260211-aarch64-pc-windows-msvc-install_only_stripped.tar.gz"
            python_sha256: "4611a41c8653fd074f75999f5ae806ee151b59828fbe7d218e02e125187263fe"
    
    runs-on: ${{ matrix.runner }}
    env:
      BINARY_NAME: adqa-${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || 'v0.0.0' }}-${{ matrix.target }}

    steps:
      - uses: actions/checkout@v5
      
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Setup MSVC for ARM64
        if: matrix.arch == 'arm64'
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: arm64

      - name: Fix PATH (prioritize MSVC over Git)
        if: matrix.arch == 'arm64'
        shell: cmd
        run: |
          set PATH=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\bin\HostARM64\arm64;%PATH%
          ren "C:\Program Files\Git\usr\bin\link.exe" link.exe.bak

      - name: Setup Standalone Python
        shell: bash
        run: |
          mkdir -p standalone_python
          cd standalone_python
          curl -sfSL "${{ matrix.python_url }}" -o python.tar.gz
          
          # checksum check
          echo "${{ matrix.python_sha256 }}  python.tar.gz" | sha256sum -c -
          
          tar -xf python.tar.gz
          mv python/ ../python_env
          cd ..

      - name: Install Backend Packages into Bundled Python
        shell: bash
        run: |
            ./python_env/python.exe -m pip install --upgrade pip setuptools wheel
            ./python_env/python.exe -m pip install "meson==1.10.0"
            
            #set PIP_NO_BUILD_ISOLATION=1
            set PIP_NO_BUILD_ISOLATION=1 && ./python_env/python.exe -m pip install .

            #./python_env/python.exe -m pip install . --prefer-binary --no-build-isolation
            mv ./python_env/python.exe ./python_env/python.exe_disable
            mv ./python_env/pythonw.exe ./python_env/pythonw.exe_disable
            set PIP_NO_BUILD_ISOLATION=

      - name: Build TUI
        working-directory: adqa-tui
        shell: bash
        run: cargo build --release --target ${{ matrix.target }}

      - name: Prepare Standalone Package
        shell: bash
        run: |
            mkdir -p ${{ env.BINARY_NAME }}/bin
            cp -r python_env/* ${{ env.BINARY_NAME }}/bin
            cp adqa-tui/target/${{ matrix.target }}/release/adqa-tui.exe ${{ env.BINARY_NAME }}/bin/
            cp adqa-tui/target/${{ matrix.target }}/release/adqa-cli.exe ${{ env.BINARY_NAME }}/bin/
            cp README.md LICENSE ${{ env.BINARY_NAME }}/
            mkdir -p ${{ env.BINARY_NAME }}/samples
            cp -r samples/* ./${{ env.BINARY_NAME }}/samples

      - name: Clean and zip
        shell: bash
        working-directory: ${{ env.BINARY_NAME }}
        run: |
            cp ../distribution/win/minify_env_win.sh ./bin/
            ./bin/minify_env_win.sh -y
            rm ./bin/minify_env_win.sh
            cd ..
            7z a -tzip '${{ env.BINARY_NAME }}.zip' './${{ env.BINARY_NAME }}/*'

      - name: Upload Zip to Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: "v0.1.0-beta"
          files: ${{ env.BINARY_NAME }}.zip
          draft: true
          prerelease: true
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.x'

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v3

      - name: Install WiX v5
        run: dotnet tool install --global wix --version 5.0.2

      - name: Build MSI Installer
        run: |
            $env:VERSION = if ("${{ env.BINARY_NAME }}" -match 'v(\d+\.\d+\.\d+)') { $matches[1] }
            wix extension add --global WixToolset.UI.wixext/5.0.2
            Copy-Item ./distribution/win/adqa-installer.wxs ./adqa-installer.wxs
            wix build ./adqa-installer.wxs -arch ${{ matrix.arch }} -ext WixToolset.UI.wixext -o "${{ env.BINARY_NAME }}-installer.msi"

      - name: Upload MSI to Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: "v0.1.0-beta"
          files: ${{ env.BINARY_NAME }}-installer.msi
          draft: true
          prerelease: true