name: Release-win-x86_64-msi-wixtool

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      TARGET: x86_64-pc-windows-msvc
      BINARY_NAME: adqa-${{ github.ref_name }}-win-x86_64
      tui_NAME: adqa-tui
      CLI_NAME: adqa-cli
      PYTHON_URL: "https://github.com/astral-sh/python-build-standalone/releases/download/20240107/cpython-3.12.1+20240107-x86_64-pc-windows-msvc-shared-pgo-full.tar.zst"
    steps:
      - uses: actions/checkout@v5
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ env.TARGET }}

      - name: Setup Standalone Python
        shell: bash
        run: |
          mkdir -p standalone_python
          cd standalone_python
          curl -sfSL "${{ env.PYTHON_URL }}" -o python.tar.zst
          tar -xf python.tar.zst
          mv python/install ../python_env
          cd ..

      - name: Install Backend Packages into Bundled Python
        run: ./python_env/python.exe -m pip install .

      - name: Build TUI
        working-directory: adqa-tui
        shell: bash
        run: cargo build --release --target ${{ env.TARGET }}
         
      - name: Prepare Standalone Package
        shell: bash
        run: |
            mkdir -p adqa-win/
            cp -r python_env/* adqa-win/
            find adqa-win/ -name "__pycache__" -type d -exec rm -rf {} + || true
            cp adqa-tui/target/${{ env.TARGET }}/release/adqa-tui.exe adqa-win/${{ env.tui_NAME }}.exe
            cp adqa-tui/target/${{ env.TARGET }}/release/adqa-cli.exe adqa-win/${{ env.CLI_NAME }}.exe
            7z a -tzip '${{ env.BINARY_NAME }}.zip' 'adqa-win\*'
      
      # Create MSI
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.x'

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v3

      - name: Install WiX v7
        run: dotnet tool install --global wix

      - name: Build MSI Installer
        run: wix build .\adqa-installer.wxs -o adqa-installer.msi

      - name: Upload MSI as artifact
        uses: actions/upload-artifact@v5
        with:
          name: ${{ env.BINARY_NAME }}-installer.msi
          path: ${{ env.BINARY_NAME }}-installer.msi

      # Disable later, just for testing builds manual without publish tags
      - name: Upload Artifact
        uses: actions/upload-artifact@v5
        with:
          name: ${{ env.BINARY_NAME }}
          path: ${{ env.BINARY_NAME }}.zip

      - name: Upload to Release
        uses: softprops/action-gh-release@v3
        with:
          files: ${{ env.BINARY_NAME }}.zip